package com.surpass.mvc.system.bas.model;


public class Courseware {
    /**主键*/
    private Long id;

    /**课程ID*/
    private Integer course_id;

    /**名称*/
    private String name;

    /**简介*/
    private String synopsis;

    /**点击量*/
    private Integer clicks;

    /**创建时间*/
    private String cjsj;

    /**排序*/
    private Integer order_index;

    /**课件文件路径*/
    private String path;
    
    private String img;

    /**介绍*/
    private String introduce;
    
    public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.id
     *
     * @return the value of t_courseware.id
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.id
     *
     * @param id the value for t_courseware.id
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.course_id
     *
     * @return the value of t_courseware.course_id
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public Integer getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.course_id
     *
     * @param course_id the value for t_courseware.course_id
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setCourse_id(Integer course_id) {
        this.course_id = course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.name
     *
     * @return the value of t_courseware.name
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.name
     *
     * @param name the value for t_courseware.name
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.synopsis
     *
     * @return the value of t_courseware.synopsis
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.synopsis
     *
     * @param synopsis the value for t_courseware.synopsis
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis == null ? null : synopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.clicks
     *
     * @return the value of t_courseware.clicks
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.clicks
     *
     * @param clicks the value for t_courseware.clicks
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.cjsj
     *
     * @return the value of t_courseware.cjsj
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.cjsj
     *
     * @param cjsj the value for t_courseware.cjsj
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.order_index
     *
     * @return the value of t_courseware.order_index
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public Integer getOrder_index() {
        return order_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.order_index
     *
     * @param order_index the value for t_courseware.order_index
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setOrder_index(Integer order_index) {
        this.order_index = order_index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.path
     *
     * @return the value of t_courseware.path
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.path
     *
     * @param path the value for t_courseware.path
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_courseware.introduce
     *
     * @return the value of t_courseware.introduce
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_courseware.introduce
     *
     * @param introduce the value for t_courseware.introduce
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}