package com.surpass.mvc.system.bas.model;

import java.util.Date;

public class MyCourse {
    /**唯一标识*/
    private String id;

    /**课程ID*/
    private Integer course_id;

    /**用户ID*/
    private String act_user_id;

    /**类型 1 我创建的课程 2 我购买的课程*/
    private Integer type;
    
    /**会员编号*/
    private Integer memberid;

    /**购买的视频开始时间*/
    private Date begindate;

    /**购买的课程结束时间*/
    private Date enddate;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_course.id
     *
     * @return the value of t_my_course.id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_course.id
     *
     * @param id the value for t_my_course.id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_course.course_id
     *
     * @return the value of t_my_course.course_id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public Integer getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_course.course_id
     *
     * @param course_id the value for t_my_course.course_id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public void setCourse_id(Integer course_id) {
        this.course_id = course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_course.act_user_id
     *
     * @return the value of t_my_course.act_user_id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public String getAct_user_id() {
        return act_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_course.act_user_id
     *
     * @param act_user_id the value for t_my_course.act_user_id
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public void setAct_user_id(String act_user_id) {
        this.act_user_id = act_user_id == null ? null : act_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_course.type
     *
     * @return the value of t_my_course.type
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_course.type
     *
     * @param type the value for t_my_course.type
     *
     * @mbggenerated Fri May 25 10:51:30 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

	public Integer getMemberid() {
		return memberid;
	}

	public void setMemberid(Integer memberid) {
		this.memberid = memberid;
	}

	public Date getBegindate() {
		return begindate;
	}

	public void setBegindate(Date begindate) {
		this.begindate = begindate;
	}

	public Date getEnddate() {
		return enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}
    
}