package linfei.dao;

import java.util.List;

import linfei.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	删除用户来自主键
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	添加用户
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	动态添加用户
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	根据主键查询用户
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */
    User selectByPrimaryKey(Integer id);
    
    /**
     * 查询所有用户
     * @return List<User>
     */
    List<User> selectAllUser();
    
    /**
     * 根据账号密码查询用户
     * @return User
     */
    User selectUserByUserAndPassword(User user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	根据主键动态修改用户
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */	
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *	根据主键修改用户
     * @mbggenerated Wed Dec 19 10:14:26 CST 2018
     */
    int updateByPrimaryKey(User record);
}