package com.surpass.mvc.system.bas.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.surpass.mvc.system.bas.model.Course;
import com.surpass.mvc.system.bas.model.CourseHot;
import com.surpass.mvc.system.bas.model.CourseRecommendBean;

public interface CourseHotMapper {

	/**
	 * 查询 信息
	 */
	List<CourseRecommendBean> query(Map<String, Object> build) throws Exception;

	/**
	 * 查询 记录数
	 */
	Integer total(Course record) throws Exception;

	Integer getCourseHotByCourseIdTotle(CourseHot record) throws Exception;

	int updateDate(CourseHot record) throws Exception;

	/**
	 * 删除
	 */
	int deleteByKey(@Param(value = "ids") String ids) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	int insert(CourseHot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	int insertSelective(CourseHot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	CourseHot selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	int updateByPrimaryKeySelective(CourseHot record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_course_hot
	 * 
	 * @mbggenerated Sat Jul 07 11:08:35 CST 2018
	 */
	int updateByPrimaryKey(CourseHot record);
}