package com.surpass.mvc.system.bas.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.surpass.mvc.system.bas.model.Courseware;

public interface CoursewareMapper {
	
	/**
	 * 
	* 方法名称：query<br>
	* 方法说明: <br>
	* 创建人: 王鹏飞<br>
	* 创建日期: 2018-8-8<br>
	* @param courseware
	* @return
	* @throws Exception
	 */
	List<Courseware> query(Courseware courseware) throws Exception;
	
	/**
	 * 删除
	 */
	int deleteByKey(@Param(value = "ids") String ids) throws Exception;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int insert(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int insertSelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    Courseware selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int updateByPrimaryKeySelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseware
     *
     * @mbggenerated Mon Aug 06 22:02:40 CST 2018
     */
    int updateByPrimaryKey(Courseware record);
}