package com.surpass.mvc.system.bas.dao;

import com.surpass.mvc.system.bas.model.MemberRakeBack;

public interface MemberRakeBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    int insert(MemberRakeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    int insertSelective(MemberRakeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    MemberRakeBack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    int updateByPrimaryKeySelective(MemberRakeBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_rakeback
     *
     * @mbggenerated Thu Nov 01 17:42:37 CST 2018
     */
    int updateByPrimaryKey(MemberRakeBack record);
}