package com.surpass.mvc.system.bas.dao;

import java.util.List;
import java.util.Map;

import com.surpass.mvc.system.bas.model.MemberPresentRecord;

public interface MemberPresentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    int insert(MemberPresentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    int insertSelective(MemberPresentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    MemberPresentRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    int updateByPrimaryKeySelective(MemberPresentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_presentrecord
     *
     * @mbggenerated Wed Oct 24 10:41:42 CST 2018
     */
    int updateByPrimaryKey(MemberPresentRecord record);
    /**
   	 * 
   	 * 方法名称：query<br>
   	 * 方法说明: 查询提现列表<br>
   	 * 创建人: 何扬<br>
   	 * 创建日期: 2018-8-29<br>
   	 * 
   	 * @param build
   	 * @return
   	 */
   	List<MemberPresentRecord> query(Map<String, Object> build);
       
       //提现记录总数
   	Integer total(MemberPresentRecord record);
   	//会员提现记录总数
   	Integer totalbymemberId(Integer memberid);
   	//获取提现记录
   	List<MemberPresentRecord> getPresentRecordByMemberId(Integer memberid,int start, int limit, String orderBy);
}