package com.surpass.mvc.system.bas.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.surpass.mvc.system.bas.model.Member;

public interface MemberMapper {
	/*会员信息查询*/
	Member selectByPrimaryKey(Integer id);
	
	/*会员信息删除*/
	int deleteByPrimaryKey(@Param(value = "ids") String ids);
	
	/*会员信息更新*/
	int updateByPrimaryKeySelective(Member member);
	
	/*会员总数*/
	Integer total(Member member);
	
	/*查询到会员上级代理的id*/
	Integer selectByTopLevel(Integer id);
	
	/**
	 * 
	 * 方法名称：query<br>
	 * 方法说明: 查询 会员数据列表<br>
	 * 创建人: 何扬<br>
	 * 创建日期: 2018-8-1<br>
	 * 
	 * @param build
	 * @return
	 */
	List<Member> query(Map<String, Object> build);
	/**
	 * 
	 * 方法名称：verifyMember<br>
	 * 方法说明: <br>
	 * 创建人: 何扬<br>
	 * 创建日期: 2018-8-1<br>
	 * 
	 * @param member
	 * @return
	 */
	int verifyMember(Member member);
	
	/**
	 * 
	 * 方法名称：selectByCommendNO<br>
	 * 方法说明: 查询推荐码<br>
	 * 创建人: 何扬<br>
	 * 创建日期: 2018-8-2<br>
	 * 
	 * @param commendNo
	 * @return
	 */
	Member selectByCommendNO(String commendNo);
	
	Member getMemberByopenId(String openId);
	
	/**
	 * 
	 * 方法名称：selectByMobilePhone<br>
	 * 方法说明: 查询手机号<br>
	 * 创建人: 何扬<br>
	 * 创建日期: 2018-8-18<br>
	 * 
	 * @param phone
	 * @return
	 */
	Member selectByMobilePhone(String mobilephone);
	
	/**
	 * 
	 * 方法名称：selectByPersonNO<br>
	 * 方法说明: 查询下级会员<br>
	 * 创建人: 何扬<br>
	 * 创建日期: 2018-8-2<br>
	 * 
	 * @param commendNo
	 * @return
	 */
	List<Member> selectByPersonNO(String commendNo);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member
     *
     * @mbggenerated Wed Aug 08 09:25:27 CST 2018
     */
    int insert(Member record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member
     *
     * @mbggenerated Wed Aug 08 09:25:27 CST 2018
     */
    int insertSelective(Member record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member
     *
     * @mbggenerated Wed Aug 08 09:25:27 CST 2018
     */
    int updateByPrimaryKey(Member record);

}
