package com.surpass.mvc.system.bas.dao;

import com.surpass.mvc.system.bas.model.MemberCollectionOpus;

public interface MemberCollectionOpusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    int insert(MemberCollectionOpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    int insertSelective(MemberCollectionOpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    MemberCollectionOpus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    int updateByPrimaryKeySelective(MemberCollectionOpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection_opus
     *
     * @mbggenerated Wed Oct 10 11:25:05 CST 2018
     */
    int updateByPrimaryKey(MemberCollectionOpus record);
}