package com.surpass.mvc.system.bas.dao;

import com.surpass.mvc.system.bas.model.MemberAccount;

public interface MemberAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    int insert(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    int insertSelective(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    MemberAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    int updateByPrimaryKeySelective(MemberAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_member_account
     *
     * @mbggenerated Wed Oct 24 09:09:35 CST 2018
     */
    int updateByPrimaryKey(MemberAccount record);
    
    MemberAccount selectByMemberId(Integer id);
}