package com.surpass.mvc.system.bas.dao;

import com.surpass.mvc.system.bas.model.MemberIdentity;

public interface MemberIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    int insert(MemberIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    int insertSelective(MemberIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    MemberIdentity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    int updateByPrimaryKeySelective(MemberIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_identity
     *
     * @mbggenerated Sat Nov 03 10:46:47 CST 2018
     */
    int updateByPrimaryKey(MemberIdentity record);
}