package com.surpass.mvc.system.bas.dao;

import java.util.List;
import java.util.Map;

import com.surpass.mvc.system.bas.model.TeacherOpus;
import com.surpass.mvc.system.bas.model.TeacherOpusHot;

public interface TeacherOpusHotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    int insert(TeacherOpusHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    int insertSelective(TeacherOpusHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    TeacherOpusHot selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherOpusHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_opus_hot
     *
     * @mbggenerated Fri Sep 21 09:44:20 CST 2018
     */
    int updateByPrimaryKey(TeacherOpusHot record);

    /**
	 * 查询作品展示 信息
	 */
	List<TeacherOpusHot> query(Map<String, Object> build) throws Exception;
	
	/**
	 * 查询 记录数
	 */
	Integer total(TeacherOpus record) throws Exception;
	
	Integer getTeacherOpusHotByTeacherIdTotal(TeacherOpusHot record) throws Exception;

	int updateDate(TeacherOpusHot record) throws Exception;
}