package com.surpass.mvc.system.bas.dao;

import java.util.List;

import com.surpass.mvc.system.bas.model.TeacherType;

public interface TeacherTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    int insert(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    int insertSelective(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    TeacherType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_type
     *
     * @mbggenerated Mon Nov 05 18:00:34 CST 2018
     */
    int updateByPrimaryKey(TeacherType record);
    
    List<TeacherType> getTeacherType(TeacherType teacherType);
}