package com.surpass.mvc.system.sys.dao;

import java.util.List;

import com.surpass.mvc.core.bean.TreeNode;
import com.surpass.mvc.system.sys.bean.DepartmentTree;
import com.surpass.mvc.system.sys.model.Department;

public interface DepartmentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	int deleteByPrimaryKey(Integer bmbh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	int insert(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	int insertSelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	Department selectByPrimaryKey(Integer bmbh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	int updateByPrimaryKeySelective(Department record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_department
	 * 
	 * @mbggenerated Tue Dec 27 17:11:52 CST 2016
	 */
	int updateByPrimaryKey(Department record);

	List<DepartmentTree> getDepartmentTreeById(Integer dept_id);

	List<DepartmentTree> getDepartmentTreeData(Department department);

	List<TreeNode> getDepartmentTreeNode(String node);

	Department selectByPath(String path);

	/**
	 * 方法名称：selectdeptId<br>
	 * 方法说明: <br>
	 * 创建人: wangli<br>
	 * 创建日期: 2017-5-24<br>
	 * @param path
	 * @return
	 */
	String selectdeptId(String path);
	

}