package com.surpass.mvc.system.sys.dao;

import com.surpass.mvc.system.sys.model.FrmAccount;

public interface FrmAccountMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int deleteByPrimaryKey(Integer account_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int insert(FrmAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int insertSelective(FrmAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	FrmAccount selectByPrimaryKey(Integer account_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int updateByPrimaryKeySelective(FrmAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int updateByPrimaryKey(FrmAccount record);

	FrmAccount selectByBean(FrmAccount frmAccount);
}