package com.surpass.mvc.system.sys.dao;

import org.apache.ibatis.annotations.Param;

import com.surpass.mvc.system.sys.model.FrmAccountUser;
import com.surpass.mvc.system.sys.model.LoginAccount;

public interface FrmAccountUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int deleteByPrimaryKey(String act_user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int insert(FrmAccountUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int insertSelective(FrmAccountUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	FrmAccountUser selectByPrimaryKey(String act_user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int updateByPrimaryKeySelective(FrmAccountUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_account_user
	 * 
	 * @mbggenerated Mon Dec 12 13:55:03 CST 2016
	 */
	int updateByPrimaryKey(FrmAccountUser record);

	/**
	 * 
	 * 方法名称：findLoginAccountByBean<br>
	 * 方法说明: 根据属性获取对象<br>
	 * 创建人: 方曙强<br>
	 * 创建日期: 2016-12-12<br>
	 * 
	 * @param parAccount
	 * @return
	 */
	LoginAccount findLoginAccountByBean(LoginAccount parAccount);

	/**
	 * 
	 * 方法名称：changeUserState<br>
	 * 方法说明: 更改用户状态<br>
	 * 创建人: 方曙强<br>
	 * 创建日期: 2016-12-22<br>
	 * 
	 * @param act_user_id
	 * @param state
	 */
	void changeUserState(@Param("ids") String[] act_user_id, @Param("state") String state);
}