package com.surpass.mvc.system.sys.dao;

import java.util.List;

import com.surpass.mvc.system.sys.bean.ComboBox;
import com.surpass.mvc.system.sys.model.FrmUserType;

public interface FrmUserTypeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	int deleteByPrimaryKey(Integer utpId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	int insert(FrmUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	int insertSelective(FrmUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	FrmUserType selectByPrimaryKey(Integer utpId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	int updateByPrimaryKeySelective(FrmUserType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table frm_user_type
	 * 
	 * @mbggenerated Mon Dec 12 09:19:30 CST 2016
	 */
	int updateByPrimaryKey(FrmUserType record);

	/**
	 * 
	 * 方法名称：getUserTypeComboxData<br>
	 * 方法说明: 获取用户类型下拉数据<br>
	 * 创建人: 方曙强<br>
	 * 创建日期: 2016-12-12<br>
	 * 
	 * @return
	 */
	List<ComboBox> getUserTypeComboxData();
}