package com.surpass.mvc.system.sys.dao;

import java.util.List;
import java.util.Map;

import com.surpass.mvc.system.sys.model.SysIntegralSet;

public interface SysIntegralSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    int deleteByPrimaryKey(String integralno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    int insert(SysIntegralSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    int insertSelective(SysIntegralSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    SysIntegralSet selectByPrimaryKey(String integralno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    int updateByPrimaryKeySelective(SysIntegralSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_integralset
     *
     * @mbggenerated Thu Oct 25 09:57:14 CST 2018
     */
    int updateByPrimaryKey(SysIntegralSet record);

    SysIntegralSet getPoint(String integralNo);
    
    List<SysIntegralSet> query(Map<String, Object> build);
    
    Integer total(SysIntegralSet sis);
}