package com.surpass.mvc.system.sys.dao;

import java.util.List;
import java.util.Map;

import com.surpass.mvc.system.sys.model.TeacherInfo;

public interface TeacherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int insert(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int insertSelective(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    TeacherInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher_info
     *
     * @mbggenerated Thu Sep 20 15:01:41 CST 2018
     */
    int updateByPrimaryKey(TeacherInfo record);
    
    /**
	 * 查询 教师信息
	 */
	List<TeacherInfo> query(Map<String, Object> build) throws Exception;

	/**
	 * 查询 记录数
	 */
	Integer total(TeacherInfo teacherInfo) throws Exception;
	
	TeacherInfo getTeacherInfoByAccoutId(String accountid) throws Exception;

}